In [3]:
a=10

In [4]:
id(a)

1463289277008

In [5]:
import numpy as np

In [6]:
data=[1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [7]:
data2=[[1,2],[3,4]]
data2

[[1, 2], [3, 4]]

In [8]:
arr=np.array(data)
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

## Univesal Function: broadcast 기능을 확장해서 , numpy array 의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 것

In [9]:
f=lambda x:1/x

arr1=np.array([1.,2.,3.])
for i in range(arr1.shape[0]):
    arr1[i]=f(arr1[i])
print(arr1)

[1.         0.5        0.33333333]


### 1.6. Indexing


## 2. Numpy Methods
     #numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

2.1  Math Functions

In [10]:
 # 표준정규분포에서 random sampling 을 한 원소를 가지는 5*3 행렬을 만든다.
mat1= np.random.randn(5,3)
mat1

array([[-0.66379427,  0.06488162, -2.06399604],
       [ 0.66998891, -0.68479199,  1.06023613],
       [-0.84466541, -0.09908021, -1.39678528],
       [ 1.10203607,  0.4690226 , -1.58379161],
       [ 0.42544491, -0.66033462,  0.285351  ]])

In [11]:
#mat1 에 절댓값 씌우기
np.abs(mat1)

array([[0.66379427, 0.06488162, 2.06399604],
       [0.66998891, 0.68479199, 1.06023613],
       [0.84466541, 0.09908021, 1.39678528],
       [1.10203607, 0.4690226 , 1.58379161],
       [0.42544491, 0.66033462, 0.285351  ]])

In [12]:
#mat 제곱하기
np.square(mat1)

array([[4.40622836e-01, 4.20962525e-03, 4.26007964e+00],
       [4.48885134e-01, 4.68940072e-01, 1.12410065e+00],
       [7.13459663e-01, 9.81688858e-03, 1.95100913e+00],
       [1.21448351e+00, 2.19982198e-01, 2.50839585e+00],
       [1.81003371e-01, 4.36041806e-01, 8.14251959e-02]])

In [14]:
#linear algebra functions
vec=np.array([1,2,3])
#1. norm
np.linalg.norm(vec)
#2. eigenvalue


3.7416573867739413